import { inter } from './fonts'
import "./globals.scss";

export const metadata = {
  title: "Comunidade Respira | Alê Montezano",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
